server:
    port: 8085
spring:
    application:
        name: simillar-issue-service
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka/
        healthcheck:
            enabled: true