version: "3"
services:
  counter-service:
    build:
      context: counter-service
      dockerfile: Dockerfile
      args:
        JAR_FILE: './target/counter-service-0.0.1-SNAPSHOT.jar'
    image: counter-service
    command: ["mvnw", "clean package"]
    ports:
    - 8761:8761
    volumes:
    - /service/counter-service
    healthcheck:
      test: "curl -f http://localhost:8761/actuator/health"
      interval: 30s
      timeout: 10s
      retries: 5
  