server:
    port: 8082
spring:
    application:
        name: gateway-service
eureka:
    instance:
        hostname: localhost
    client:
        fetchRegistry: true
        service-url:
            defaultZone: http://${eureka.instance.hostname}:8081/eureka/   
zuul:
    ignored-services: "*" # Disable accessing services using service name (i.e. name-service). They should be only accessed through the path defined below.
    routes:
        village-services:
            path: /village-services/**
            service-id: village-services
        counter-services:
            path: /counter-services/**
            serviceId: counter-services
documentation: 
    baseurl: http://localhost
    swagger: 
        services:   
          - 
              name: counter-services
              url: ${documentation.baseurl}:8084/v2/api-docs
              version: 1.0
          - 
              name: village-services
              url: ${documentation.baseurl}:8083/v2/api-docs
              version: 1.0
