server:
    port: 8084
spring:
    application:
        name: counter-services
    datasource:
        driver-class-name: org.h2.Driver
        password: sa
        url: jdbc:h2:mem:zenhomes;
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
    liquibase:
        change-log: classpath:/config/liquibase/master.xml
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka/
        healthcheck:
            enabled: true
logging:
    level:
        liquibase: INFO